### ISSUE TITLE
CompressedXmlParser.getStringFromStringTable method throwing a ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AymenDaoudi** [xgouchet/AXML#7]
When the parser seems to encounter an element with an attribute that has a long value, the **getStringFromStringTable** method throws an **ArrayIndexOutOfBoundsException**.

![image](https://user-images.githubusercontent.com/1885298/34657774-b2bfd0ba-f3f7-11e7-8984-d70cbd469a17.png)

Here exactly : 

![image](https://user-images.githubusercontent.com/1885298/34657786-da8222e2-f3f7-11e7-8297-f09010c7b425.png)

The file causing this behavior looks like this : 

![image](https://user-images.githubusercontent.com/1885298/34657807-03246e08-f3f8-11e7-86b3-b534555b64a0.png)

**Comment by sujeathpareddy** [comment]
I have the same issue. Stack trace is below:

```
    java.lang.ArrayIndexOutOfBoundsException: length=452; index=452
        at fr.xgouchet.axml.CompressedXmlParser.getStringFromStringTable(CompressedXmlParser.java:423)
        at fr.xgouchet.axml.CompressedXmlParser.parseStringTable(CompressedXmlParser.java:180)
        at fr.xgouchet.axml.CompressedXmlParser.parseCompressedXml(CompressedXmlParser.java:108)
        at fr.xgouchet.axml.CompressedXmlParser.parse(CompressedXmlParser.java:73)
        at fr.xgouchet.axml.CompressedXmlParser.parseDOM(CompressedXmlParser.java:89)
        at com.fizzy.be.ar.StringExtractor$Companion.handleBinaryXML(StringExtractor.kt:127)
```

**Comment by sujeathpareddy** [comment]
I seem to occasionally receive `NegativeArraySizeException` and `NullPointerException: listener must not be null` too. This is such a useful library. Fixing these bugs is better than having to rip code out of the AAPT repo.
